build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
          - js-scrutinizer-run
            coverage:
              file: coverage/clover.xml
              format: clover
