build:
  nodes:
    coverage:
      tests:
        override: [js-scrutinizer-run]
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
